# Generated by Django 3.1.7 on 2021-04-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idealab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='ub_email',
            new_name='email',
        ),
    ]
