# Generated by Django 3.1.7 on 2021-04-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idealab', '0003_auto_20210419_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='create_date',
            new_name='release_date',
        ),
    ]
