# Generated by Django 3.1.7 on 2021-04-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealab', '0004_auto_20210419_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approval status'),
        ),
    ]
