# Generated by Django 3.1.7 on 2021-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealab', '0005_idea_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='release_date',
            field=models.DateField(verbose_name='date released'),
        ),
    ]
