# Generated by Django 3.2 on 2021-06-02 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealab', '0006_auto_20210419_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='release_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date released'),
        ),
    ]
