# Generated by Django 3.2.3 on 2021-06-05 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealab', '0007_alter_idea_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='release_date',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='date released'),
        ),
    ]
