# Generated by Django 3.2.3 on 2021-06-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idealab', '0008_alter_idea_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idealab.author'),
        ),
    ]
