# Generated by Django 3.2.6 on 2021-08-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealab', '0009_auto_20210605_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
