# Generated by Django 3.1.7 on 2021-04-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_id', models.CharField(max_length=8, unique=True, verbose_name='id')),
                ('github', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('contributors', models.ManyToManyField(to='main.Contributor')),
            ],
        ),
    ]
