# Generated by Django 3.2 on 2021-04-24 00:41

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_auto_20210421_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='member',
            name='exp_grad_year',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
