# Generated by Django 3.2 on 2021-04-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_auto_20210424_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='exp_grad_year',
            field=models.IntegerField(),
        ),
    ]
