# Generated by Django 3.2 on 2021-04-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_alter_member_exp_grad_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='exp_grad_year',
        ),
    ]
