# Generated by Django 3.2 on 2021-04-24 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0006_remove_member_exp_grad_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='exp_grad_year',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
