# Generated by Django 3.2.3 on 2021-06-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('discord_id', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
